[package]
name = "brain"
version = "0.1.0"
authors = ["Angel Alonso Fonseca <alonsofonseca.angel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
clap = "2.33.1"
tokio-serial = "4.3.3"
tokio = { version = "0.2.0", features = ["io-driver"], default-features = false }
mio-serial = { version = "3.3.0", default-features = false }
futures = "0.3.1"
tokio-util = { version = "0.2.0", features = ["codec"], default-features = false }
bytes = "0.5"
log = "0.4"

[dev-dependencies]
futures = "0.3.1"
tokio = { version = "0.2.0", features = ["macros"], default-features = false }
tokio-util = { version = "0.2.0", features = ["codec"], default-features = false }
bytes = "0.5"
