[package]
name = "roctl"
version = "0.1.0"
authors = ["Angel Alonso Fonseca <alonsofonseca.angel@gmail.com>"]
edition = "2018"

[dependencies]
docopt = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8.7"
