[package]
name = "action_clients"
version = "0.1.0"
edition = "2021"

[dependencies]
rclrust = { git = "https://github.com/rclrust/rclrust.git", features = ["rolling"] }
rclrust-msg = { git = "https://github.com/rclrust/rclrust.git" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
